Release 1.5.0 - Add internalization
nordigen/nordigen-bank-ui pull request #26
Opened 2022-10-17 16:08 UTC by victory-sokolov

2022-10-19 10:48 UTC, janisskuja requested changes
Overall - looks good, just fix the indent, please.

2022-10-19 10:48 UTC, janisskuja commented on package/src/selector.js
> +const obInstitutionModalHeader = document.getElementsByClassName(
Why not add ID to the header element and get it that way? (Same way you did for `institution-modal-content`)

2022-10-19 10:48 UTC, janisskuja commented on package/src/selector.js
> +    input.setAttribute('placeholder', `${i18n.search}...`);
A problem for future - what if a translation includes a `.` somewhere in the middle?

I'd suggest using keys like `search` `go_back` `select_your_bank` in `translation.js` and have the values with all the `...` etc..

And if value for key is not available, show the key as is... so it's visible, that there's a missing translation. (alternatively, just make sure `en` has all the translations and fall back to that, if key's not found)

Currently, of course, it works the way it is.

2022-10-19 10:48 UTC, janisskuja commented on package/src/selector.js
> +const institutionList = Array.from(
Fix indent

2022-10-19 10:52 UTC, janisskuja commented on package/src/selector.js
> +    input.setAttribute('placeholder', `${i18n.search}...`);
that said, `.` in keys shouldn't be a problem if accessed via `[]` operator... `-` however are a problem

2022-10-20 05:20 UTC, janisskuja approved these changes

2022-10-21 10:24 UTC, mr-andersons approved these changes

2022-10-21 10:25 UTC, merged